[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"
  autoLaunch = false
